[build]
builder = "NIXPACKS"
buildCommand = "cd server && pip install -r requirements.txt"

[deploy]
startCommand = "cd server && python proxy_server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Environment variables - Set these in Railway dashboard
# N8N_WEBHOOK_BASE_URL = "https://your-ngrok-domain.ngrok.io"
# ALLOWED_ORIGINS = "https://your-frontend.vercel.app"
# PORT = "8000" (Railway provides this automatically)
