services:
  # InkFlow Proxy Server
  - type: web
    name: inkflow-proxy
    runtime: python
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && python proxy_server.py
    envVars:
      - key: N8N_WEBHOOK_BASE_URL
        value: https://inkflow.eu.ngrok.io
      - key: ALLOWED_ORIGINS
        value: http://localhost:8000,http://127.0.0.1:8000
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: MAX_FILE_SIZE_MB
        value: 10
      - key: MAX_FILES_PER_REQUEST
        value: 5
      - key: MAX_CONCURRENT_CONNECTIONS
        value: 50
      - key: REQUEST_TIMEOUT_SECONDS
        value: 30
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /api/health
